export const MATCHING_DEFAULT_RADIUS_KM = 5;
export const MATCHING_MAX_RADIUS_KM = 15;
export const MATCHING_RADIUS_STEP_KM = 5;
export const MATCHING_OFFER_TIMEOUT_SECONDS = 20;
export const MATCHING_MAX_CANDIDATES_PER_RADIUS = 10;
