ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'TOP_UP';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'TRIP_COMMISSION';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'ADJUSTMENT';

ALTER TABLE "Driver" ADD COLUMN "balance" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Driver" ADD COLUMN "commissionRatePercent" INTEGER NOT NULL DEFAULT 10;

ALTER TABLE "Transaction" ADD COLUMN "amount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Transaction" ADD COLUMN "description" TEXT;
